export interface Skill { name: string; icon: string; category: string }

export const SKILLS: Skill[] = [
  { name: 'Python', icon: 'python', category: 'Languages' },
  { name: 'SQL', icon: 'sql', category: 'Languages' },
  { name: 'Java', icon: 'java', category: 'Languages' },
  { name: 'VBA', icon: 'vba', category: 'Languages' },
  { name: 'Next.js', icon: 'nextjs', category: 'Frameworks' },
  { name: 'React', icon: 'react', category: 'Frameworks' },
  { name: 'Node.js', icon: 'nodejs', category: 'Frameworks' },
  { name: 'Express', icon: 'express', category: 'Frameworks' },
  { name: 'FastAPI', icon: 'fastapi', category: 'Frameworks' },
  { name: 'Tailwind CSS', icon: 'tailwind', category: 'Frameworks' },
  { name: 'NumPy', icon: 'numpy', category: 'Data & ML' },
  { name: 'Pandas', icon: 'pandas', category: 'Data & ML' },
  { name: 'Scikit-learn', icon: 'scikit', category: 'Data & ML' },
  { name: 'PyTorch', icon: 'pytorch', category: 'Data & ML' },
  { name: 'Jupyter', icon: 'jupyter', category: 'Data & ML' },
  { name: 'Airflow', icon: 'airflow', category: 'Data & ML' },
  { name: 'dbt', icon: 'dbt', category: 'Data & ML' },
  { name: 'Databricks', icon: 'databricks', category: 'Data & ML' },
  { name: 'Vapi.ai', icon: 'vapi', category: 'Tools' },
  { name: 'Airtable', icon: 'airtable', category: 'Tools' },
  { name: 'Git', icon: 'git', category: 'Tools' },
  { name: 'OpenAI', icon: 'openai', category: 'Tools' },
  { name: 'Power Automate', icon: 'powerautomate', category: 'Tools' },
  { name: 'Power BI', icon: 'powerbi', category: 'Tools' },
  { name: 'Power Apps', icon: 'powerapps', category: 'Tools' },
  { name: 'AWS', icon: 'aws', category: 'Cloud & Infra' },
  { name: 'Azure', icon: 'azure', category: 'Cloud & Infra' },
  { name: 'BigQuery', icon: 'bigquery', category: 'Cloud & Infra' },
  { name: 'Vercel', icon: 'vercel', category: 'Cloud & Infra' },
  { name: 'Railway', icon: 'railway', category: 'Cloud & Infra' },
  { name: 'GitHub', icon: 'github', category: 'Cloud & Infra' },
  { name: 'Premiere Pro', icon: 'premierepro', category: 'Video & VFX' },
  { name: 'After Effects', icon: 'aftereffects', category: 'Video & VFX' },
]

export const SKILL_CATEGORIES = ['Languages', 'Frameworks', 'Data & ML', 'Tools', 'Cloud & Infra', 'Video & VFX']
